// Auto-generated by: npx supabase gen types typescript --local > types/database.ts
// This is a stub — run the command above after linking your Supabase project.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      contractor_profiles: {
        Row: {
          id: string
          company_name: string
          display_name: string
          license_number: string | null
          phone: string | null
          email: string
          logo_url: string | null
          address_line1: string | null
          city: string | null
          state: string | null
          zip: string | null
          default_labor_rate: number
          default_markup_pct: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['contractor_profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['contractor_profiles']['Insert']>
      }
      subscriptions: {
        Row: {
          id: string
          contractor_id: string
          stripe_customer_id: string
          stripe_sub_id: string | null
          plan_id: string | null
          status: string
          current_period_end: string | null
          packet_credits: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['subscriptions']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['subscriptions']['Insert']>
      }
      clients: {
        Row: {
          id: string
          contractor_id: string
          first_name: string
          last_name: string
          address_line1: string
          address_line2: string | null
          city: string
          state: string
          zip: string
          phone: string | null
          email: string | null
          referral_source: string | null
          referral_notes: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['clients']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['clients']['Insert']>
      }
      jobs: {
        Row: {
          id: string
          contractor_id: string
          client_id: string
          job_number: string
          title: string | null
          status: string
          notes: string | null
          site_address_override: string | null
          permit_jurisdiction: string | null
          created_at: string
          updated_at: string
          sent_at: string | null
          accepted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['jobs']['Row'], 'id' | 'job_number' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['jobs']['Insert']>
      }
      job_areas: {
        Row: {
          id: string
          job_id: string
          area_type: 'bathroom' | 'entryway'
          area_label: string | null
          area_order: number
          current_condition: string | null
          notes: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['job_areas']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['job_areas']['Insert']>
      }
      job_area_modifications: {
        Row: {
          id: string
          job_area_id: string
          modification_key: string
          is_selected: boolean
          material_tier: 'economy' | 'standard' | 'premium'
          quantity: number | null
          unit: string | null
          measurement_notes: string | null
          permit_required: boolean
          risk_flags: string[]
          contractor_notes: string | null
          override_unit_cost: number | null
          override_labor_cost: number | null
          sort_order: number
        }
        Insert: Omit<Database['public']['Tables']['job_area_modifications']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['job_area_modifications']['Insert']>
      }
      scope_line_items: {
        Row: {
          id: string
          job_id: string
          job_area_id: string | null
          modification_id: string | null
          line_number: number | null
          category: string
          description: string
          scope_description: string | null
          customer_description: string | null
          quantity: number
          unit: string | null
          unit_material_cost: number
          unit_labor_cost: number
          markup_pct: number
          total_material: number
          total_labor: number
          total_line: number | null
          is_included: boolean
          sort_order: number
        }
        Insert: Omit<Database['public']['Tables']['scope_line_items']['Row'], 'id' | 'total_material' | 'total_labor'>
        Update: Partial<Database['public']['Tables']['scope_line_items']['Insert']>
      }
      proposal_packets: {
        Row: {
          id: string
          job_id: string
          version: number
          storage_path: string | null
          generated_at: string
          packet_type: string
          stripe_charge_id: string | null
        }
        Insert: Omit<Database['public']['Tables']['proposal_packets']['Row'], 'id' | 'generated_at'>
        Update: Partial<Database['public']['Tables']['proposal_packets']['Insert']>
      }
      email_logs: {
        Row: {
          id: string
          job_id: string
          resend_id: string | null
          template_key: string
          sent_at: string
          recipient_email: string
          status: string
        }
        Insert: Omit<Database['public']['Tables']['email_logs']['Row'], 'id' | 'sent_at'>
        Update: Partial<Database['public']['Tables']['email_logs']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
